(function(){
const PHONE='919465263877',EMAIL='kunalkhurana@makoverseas.com',products=window.MAK_PRODUCTS||[],categories=window.MAK_CATEGORIES||[],headCategories=window.MAK_HEAD_CATEGORIES||[],$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let cart=JSON.parse(localStorage.getItem('makClaudeCart')||'[]');
function langText(item,field){return window.MAKLanguage?.productText?.(item,field)||item?.[field]||''}
function categoryText(item,field){return window.MAKLanguage?.categoryText?.(item,field)||item?.[field]||''}
function productLabel(p){const pn=(p.partNumbers||[]).filter(x=>x&&x!=='On request').join(', '),name=langText(p,'name')||p.name;return pn?`${name} (${pn})`:name}
function save(){localStorage.setItem('makClaudeCart',JSON.stringify(cart));renderCart();updateCount()}
function updateCount(){$$('.cart-count').forEach(el=>el.textContent=cart.reduce((s,i)=>s+i.qty,0))}
function addToCart(id){const p=products.find(x=>x.id===id)||{id,name:id,partNumbers:[]},title=productLabel(p),item=cart.find(i=>i.id===id);if(item)item.qty++;else cart.push({id,title,qty:1,partNumbers:p.partNumbers||[]});save();$('#cartPanel')?.classList.add('open')}
function enquire(id){const p=products.find(x=>x.id===id),title=p?productLabel(p):id,msg=`Hello MAK Overseas, I want to enquire about:\n${title}\n\nMachine model:\nQuantity:\nLocation:`;window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(msg)}`,'_blank')}
function emailEnquire(id){const p=products.find(x=>x.id===id),title=p?productLabel(p):id,subject=`Product enquiry - ${title}`,body=`Hello MAK Overseas,\n\nI want to enquire about:\n${title}\n\nName:\nPhone:\nMachine model:\nQuantity:\nLocation:\n\nPlease share quote and availability.`;location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function renderCart(){const box=$('#cartItems');if(!box)return;box.innerHTML=cart.length?cart.map((i,idx)=>`<div class="cart-item"><div><strong>${esc(i.title)}</strong><small>${esc((i.partNumbers||[]).join(', '))}</small><div class="qty"><button data-qty="down" data-index="${idx}">-</button><span>${i.qty}</span><button data-qty="up" data-index="${idx}">+</button></div></div><button class="close" data-remove="${idx}">&times;</button></div>`).join(''):'<p style="color:#999;padding:1rem">Your enquiry cart is empty.</p>'}
function normalizeSearch(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function searchableText(p){return [p.name,p.code,(p.partNumbers||[]).join(' '),p.material,p.category,p.headCategory,p.subcategory,p.brandGroup,p.filterType,p.application,p.boxDimension,p.notes,p.desc,p.source,window.MAKLanguage?.searchText?.(p)].join(' ').toLowerCase()}
function searchMatches(p,query){
  const raw=query.trim().toLowerCase();
  if(!raw)return true;
  const text=searchableText(p),compact=normalizeSearch(text);
  return raw.split(/\s+/).every(term=>{const compactTerm=normalizeSearch(term);return text.includes(term)||(compactTerm&&compact.includes(compactTerm))});
}
function searchText(p){const base=searchableText(p),extra=window.MAKLanguage?.searchText?.(p)||'';return `${base} ${extra} ${normalizeSearch(base)} ${normalizeSearch(extra)}`}
function partLine(p){const parts=(p.partNumbers||[]).join(', ');return `<div class="part-line"><b>Part No:</b> ${esc(parts||'Available on request')}</div>`}
function detailPage(p){return p.detailPage||p.page}
function productGroupLabel(p){const head=p.headCategory||p.category||'',sub=p.subcategory||'';return head&&sub&&head!==sub?`${head} / ${sub}`:(head||sub||langText(p,'category'))}
function categorySearchText(c){return [c.title,c.summary,c.headTitle,c.headCategory,c.titleTh,c.summaryTh].join(' ').toLowerCase()}
function productCard(p){const code=p.code?`<div><b>Code:</b> ${esc(p.code)}</div>`:'',notes=p.notes?`<div><b>Note:</b> ${esc(langText(p,'notes'))}</div>`:'',subcategory=p.subcategory?`<div><b>Subcategory:</b> ${esc(p.subcategory)}</div>`:'',brand=p.brandGroup?`<div><b>Brand group:</b> ${esc(p.brandGroup)}</div>`:'',application=p.application?`<div><b>Application:</b> ${esc(p.application)}</div>`:'',box=p.boxDimension?`<div><b>Box / dimensions:</b> ${esc(p.boxDimension)}</div>`:'';return `<article class="card reveal" data-search="${esc(searchText(p))}"><a class="imgbox" href="${esc(detailPage(p))}"><img src="${esc(p.image)}" alt="${esc(langText(p,'name'))}" loading="lazy"></a><div class="body"><div class="tag">${esc(productGroupLabel(p))}</div><a class="name" href="${esc(detailPage(p))}">${esc(langText(p,'name'))}</a>${partLine(p)}<div class="meta">${code}<div><b>Material:</b> ${esc(langText(p,'material')||'Available on request')}</div>${brand}${application}${box}${subcategory}${notes}</div><p class="desc">${esc(langText(p,'desc'))}</p><div class="actions"><button class="buy" data-add="${esc(p.id)}">Add to Cart</button><a class="ghost" href="${esc(detailPage(p))}">Details</a><button class="whatsapp" data-enquire="${esc(p.id)}">WhatsApp</button><button class="email" data-email="${esc(p.id)}">Email</button></div></div></article>`}
function filterLogo(group){if(/JCB/i.test(group))return '<span class="brand-logo brand-logo-jcb">JCB</span>';if(/Komatsu/i.test(group))return '<span class="brand-logo brand-logo-komatsu">KOMATSU</span>';if(/Tata|Ashok|Leyland|AL/i.test(group))return '<span class="brand-logo brand-logo-tata">TATA</span><span class="brand-logo brand-logo-al">AL</span>';return '<span class="brand-logo brand-logo-mak">MAK</span>'}
function filterGroupPage(group){if(/JCB/i.test(group))return 'jcb-filters.html';if(/Komatsu/i.test(group))return 'komatsu-filters.html';if(/Tata|Ashok|Leyland/i.test(group))return 'tata-leyland-filters.html';return `search.html?q=${encodeURIComponent(group)}`}
function filterGroupSection(group,list){return `<section class="filter-brand-section reveal"><div class="filter-brand-head"><div><div class="filter-brand-logos">${filterLogo(group)}</div><h2>${esc(group)}</h2><p>${list.length} filter references. Search by part number, application, filter type or brand.</p></div><a class="ghost" href="${esc(filterGroupPage(group))}">Open ${esc(group)}</a></div><div class="filter-product-grid">${list.map(productCard).join('')}</div></section>`}
function categoryCard(c){return `<article class="card category-card reveal" data-search="${esc(categorySearchText(c))}"><a class="imgbox" href="${esc(c.page)}"><img src="${esc(c.image)}" alt="${esc(categoryText(c,'title'))}" loading="lazy"></a><div class="body"><div class="tag">${esc(c.headTitle||c.headCategory||'MAK Category')} · ${c.count} products</div><div class="name">${esc(categoryText(c,'title'))}</div><p class="desc">${esc(categoryText(c,'summary'))}</p><div class="actions"><a class="ghost" href="${esc(c.page)}">View Products</a></div></div></article>`}
function headCategorySection(head){const subs=categories.filter(c=>c.headSlug===head.slug);return `<section class="head-category-section reveal" id="${esc(head.slug)}" data-search="${esc((head.title+' '+head.summary+' '+subs.map(categorySearchText).join(' ')).toLowerCase())}"><div class="head-card"><div><div class="tag">${esc(head.count||0)} products · ${esc(head.subcategoryCount||subs.length)} subcategories</div><h2>${esc(head.title)}</h2><p>${esc(head.summary)}</p></div><a class="ghost" href="search.html?q=${encodeURIComponent(head.title)}">Search ${esc(head.title)}</a></div><div class="subcategory-grid">${subs.map(categoryCard).join('')}</div></section>`}
function attachReveal(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>obs.observe(el))}
function filterCards(q){const raw=q.trim().toLowerCase(),compactTerm=normalizeSearch(raw);$$('[data-search]').forEach(card=>{const text=card.dataset.search||'',compact=normalizeSearch(text);card.style.display=!raw||text.includes(raw)||(compactTerm&&compact.includes(compactTerm))?'flex':'none'})}
function drawProductsPage(){const grid=$('#categoryGrid');if(!grid)return;grid.classList.toggle('head-grid',!!headCategories.length);grid.innerHTML=(headCategories.length?headCategories.map(headCategorySection).join(''):categories.map(categoryCard).join(''));const all=$('#allProductGrid');if(all)all.innerHTML=products.map(productCard).join('');$('#filterInput')?.addEventListener('input',e=>filterCards(e.target.value));attachReveal();if(location.hash)setTimeout(()=>$(location.hash)?.scrollIntoView({block:'start'}),80)}
function drawCategoryPage(){const grid=$('#productGrid');if(!grid)return;const slug=grid.dataset.category,brandGroup=grid.dataset.brandGroup;let list=products.filter(p=>p.categorySlug===slug);if(brandGroup)list=list.filter(p=>(p.brandGroup||'General Filters')===brandGroup);$('#itemCount')&&( $('#itemCount').textContent=`${list.length} products` );grid.classList.toggle('filter-grouped-grid',slug==='filters'&&!brandGroup);if(slug==='filters'&&!brandGroup){const preferred=['JCB Filters','Komatsu Filters','Tata & Ashok Leyland Filters','General Filters'];const order=group=>{const idx=preferred.indexOf(group);return idx===-1?preferred.length:idx};const groups=[...new Set(list.map(p=>p.brandGroup||'General Filters'))].sort((a,b)=>order(a)-order(b)||a.localeCompare(b));grid.innerHTML=groups.map(group=>filterGroupSection(group,list.filter(p=>(p.brandGroup||'General Filters')===group))).join('')||'<p class="notice">No products found.</p>'}else{grid.innerHTML=list.map(productCard).join('')||'<p class="notice">No products found.</p>'}$('#filterInput')?.addEventListener('input',e=>filterCards(e.target.value));document.addEventListener('click',e=>{const btn=e.target.closest('[data-filter-query]');if(!btn)return;const input=$('#filterInput');if(input){input.value=btn.dataset.filterQuery;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}});attachReveal()}
function drawSearchPage(){const grid=$('#searchGrid');if(!grid)return;const input=$('#searchAll'),initial=new URLSearchParams(location.search).get('q')||'';if(input)input.value=initial;function draw(q){const list=products.filter(p=>searchMatches(p,q));$('#itemCount')&&( $('#itemCount').textContent=`${list.length} results` );grid.innerHTML=list.map(productCard).join('')||'<p class="notice">No products found. Try a product name, code, material, or part number like 990/14900, 99014900, or 990-14900.</p>';attachReveal()}input?.addEventListener('input',e=>draw(e.target.value));draw(initial)}
function initCart(){const panel=$('#cartPanel'),checkout=$('#checkoutBtn');if(checkout&&!$('#emailCheckoutBtn'))checkout.insertAdjacentHTML('afterend','<button class="checkout email-checkout" id="emailCheckoutBtn">Send Enquiry by Email</button>');$('#openCart')?.addEventListener('click',()=>panel?.classList.add('open'));$('[data-close-cart]')?.addEventListener('click',()=>panel?.classList.remove('open'));panel?.addEventListener('click',e=>{if(e.target.id==='cartPanel')panel.classList.remove('open')});checkout?.addEventListener('click',()=>{if(!cart.length)return;const lines=cart.map((i,n)=>`${n+1}. ${i.title} x ${i.qty}`).join('\n');window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent('Hello MAK Overseas, I want to enquire about:\n\n'+lines+'\n\nName:\nPhone:\nMachine model:\nLocation:')}`,'_blank')});$('#emailCheckoutBtn')?.addEventListener('click',()=>{if(!cart.length)return;const lines=cart.map((i,n)=>`${n+1}. ${i.title} x ${i.qty}`).join('\n');location.href=`mailto:${EMAIL}?subject=${encodeURIComponent('MAK Overseas enquiry cart')}&body=${encodeURIComponent('Hello MAK Overseas,\n\nI want to enquire about:\n\n'+lines+'\n\nName:\nPhone:\nMachine model:\nLocation:')}`});document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){addToCart(add.dataset.add);return}const en=e.target.closest('[data-enquire]');if(en){enquire(en.dataset.enquire);return}const em=e.target.closest('[data-email]');if(em){emailEnquire(em.dataset.email);return}const rm=e.target.closest('[data-remove]');if(rm){cart.splice(Number(rm.dataset.remove),1);save();return}const qty=e.target.closest('[data-qty]');if(qty){const idx=Number(qty.dataset.index);if(qty.dataset.qty==='up')cart[idx].qty++;else cart[idx].qty--;if(cart[idx]?.qty<1)cart.splice(idx,1);save();return}});renderCart();updateCount()}
window.MAKCatalogue={addToCart,enquire,emailEnquire,productLabel};
function redrawLanguageAware(){window.MAKLanguage?.enhanceProductDatabase?.();drawProductsPage();drawCategoryPage();drawSearchPage()}
document.addEventListener('DOMContentLoaded',()=>{redrawLanguageAware();initCart();attachReveal()});
window.addEventListener('mak-language-change',()=>{redrawLanguageAware();renderCart();updateCount()});
})();
